#!/bin/bash

log=$(mktemp)

enable_logging () {
    exec 3>&1 4>&2
    exec &> "$log"
}

disable_logging () {
    exec 1>&3 2>&4
}

print_log () {
    disable_logging
    cat "$log"
}

cleanup () {
    disable_logging
    rm -f "$log"
}

error_handler () {
    script_name="$0"
    line="$1"
    exit_code="$2"
    echo "${script_name}: Error in line $line (exit code ${exit_code})"
    print_log
    cleanup
    exit $exit_code
}

trap 'error_handler ${LINENO} $?' ERR INT TERM
enable_logging
apt-get update || print_log
apt-get install salt-minion -y || print_log
salt-call state.apply --retcode-passthrough

# Also ensure salt-minion is running
if ! systemctl is-active salt-minion; then
    systemctl restart salt-minion
fi
trap - ERR INT TERM

cleanup
