#!/bin/sh

service="{{ config.service }}"
config="{{ config.config_file }}"

[ "${ADDRFAM}" = "inet" ] || exit 0
grep "${IFACE}" "${config}" > /dev/null || exit 0

if systemctl is-active ${service} > /dev/null; then
    systemctl restart ${service}
fi
