#!/bin/bash

# Defaults
BACKUP_DIR="${HOME}/mariadb-backup"
KEEP_DAILY=7
KEEP_MONTHLY=6
MYSQLDUMP="/usr/bin/mysqldump"
CONFIG="/etc/mariadb-backup/config"

. "${CONFIG}"

declare -A keep
keep["daily"]=${KEEP_DAILY}
keep["monthly"]=${KEEP_MONTHLY}

INTERVAL="${1,,}"
TIMESTAMP=$(date +'%Y-%m-%d-%H%M%S')
BACKUP_FILE="${BACKUP_DIR}/mariadb-${INTERVAL}-${TIMESTAMP}.xz"


log () {
    echo "$(date --rfc-3339=seconds) $@"
}

log_err () {
    >&2 log "$@"
}

check_interval () {
    for i in ${!keep[@]}; do
        [[ ${INTERVAL} == ${i} ]] && return
    done

    log_err "${INTERVAL} is not a valid interval"
    exit 1
}

backup_dbs () {
    local INCOMPLETE="${BACKUP_FILE}.incomplete"

    log "Dumping all databases to ${BACKUP_FILE}"
    local UMASK_CURRENT=$(umask)
    umask 0077

    [[ -d ${BACKUP_DIR} ]] || mkdir "${BACKUP_DIR}"
    "${MYSQLDUMP}" --all-databases | xz > "${INCOMPLETE}"
    mv "${INCOMPLETE}" "${BACKUP_FILE}"
    du -h "${BACKUP_FILE}"

    umask ${UMASK_CURRENT}
    log "Finished dumping all databases"
}

enforce_retention () {
    log "Removing incomplete backups"
    find "${BACKUP_DIR}" -name "*.incomplete" \
        | xargs --no-run-if-empty --max-args 1 rm -v

    log "Removing old backups"
    find "${BACKUP_DIR}" -name "*-${INTERVAL}-*" \
        | sort \
        | head -n -${keep[${INTERVAL}]} \
        | xargs --no-run-if-empty --max-args 1 rm -v
}


set -e

check_interval
backup_dbs
enforce_retention
