docker:
  ce_package: docker-ce
  service: docker
  repo: deb https://download.docker.com/linux/debian {{ grains['oscodename'] }} stable
  key_url: https://download.docker.com/linux/debian/gpg
  config:
    weekly_cleanup: false
    daemon: {}
