#!/bin/sh

UPTIME=$(uptime -p)
USERS=$(users | wc -w)
OS=$(which lsb_release > /dev/null && lsb_release -ds)
MEM_TOTAL=$(free -h | awk '/Mem:/ {print $2}')
CPU_MODEL=$(lscpu | awk -F ': +' '/^Model name:/ {print $2}')
CPU_COUNT=$(lscpu | awk -F ': +' '/^CPU\(s\):/ {print $2}')
CPU_SOCKETS=$(lscpu | awk -F ': +' '/^Socket\(s\):/ {print $2}')
CPU_CORES=$(lscpu | awk -F ': +' '/^Core\(s\) per socket:/ {print $2}')
CPU_THREADS=$(lscpu | awk -F ': +' '/^Thread\(s\) per core:/ {print $2}')

printf " Operating system : %s\n" "${OS}"
printf " CPU              : %s\n" "${CPU_COUNT} x ${CPU_MODEL}"
printf "                    %s\n" "${CPU_SOCKETS} socket(s) with ${CPU_CORES} core(s) per socket and ${CPU_THREADS} thread(s) per core"
printf " Memory           : %s\n" "${MEM_TOTAL}"
printf " Uptime           : %s\n" "${UPTIME}"
printf " Users logged in  : %s\n" "${USERS}"
echo
